import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  late Map<String, String> _localizedStrings;

  // Hardcoded dictionary for now to avoid async loading issues during MVP
  // In production, this can be moved to JSON assets
  final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'settings_title': 'Settings',
      'common_section': 'General',
      'language_tile': 'Language',
      'theme_tile': 'Dark Mode',
      'theme_subtitle': 'Switch to dark appearance',
      'notifications_section': 'Notifications',
      'push_notif': 'Push Notifications',
      'push_notif_sub': 'Barter info & incoming chats',
      'email_notif': 'Email Newsletter',
      'email_notif_sub': 'Feature updates & promos',
      'about_section': 'About',
      'app_version': 'App Version',
      'privacy_policy': 'Privacy Policy',
      'terms_conditions': 'Terms & Conditions',
      'account_section': 'Account',
      'delete_account': 'Delete Account',
      'delete_account_sub': 'This action cannot be undone',
      'rights_reserved': 'SkillBarter © 2026',
      'select_language': 'Select Language',
      // Navigation
      'nav_home': 'Home',
      'nav_explore': 'Explore',
      'nav_radar': 'Radar',
      'nav_trans': 'Transactions',
      'nav_profile': 'Profile',
      // Profile
      'info_title': 'Personal Info',
      'label_nik': 'ID Number',
      'label_gender': 'Gender',
      'gender_male': 'Male',
      'gender_female': 'Female',
      'label_dob': 'Date of Birth',
      'label_city': 'City',
      'label_job': 'Job',
      'label_edu': 'Education',
      'menu_password': 'Change Password',
      'menu_help': 'Help Center',
      'stat_trans': 'Transactions',
      'stat_hours': 'Hours',
      // Home
      'welcome_sub': 'What skill do you want to trade today?',
      'stat_rating': 'Rating',
      'stat_coins': 'SkillCoin',
      'stat_hours_contrib': 'Contrib. Hours',
      'quick_actions': 'Quick Actions',
      'action_add_skill': 'Add Skill',
      'action_add_skill_sub': 'Start sharing',
      'action_search': 'Find Skill',
      'action_search_sub': 'Find mentor',
      'action_leaderboard': 'Leaderboard',
      'action_leaderboard_sub': 'Top users',
      'action_history': 'History',
      'action_history_sub': 'Activity Log',
      // Auth
      'auth_login_title': 'Login',
      'auth_register_title': 'Create Account',
      'auth_welcome_title': 'SkillBarter',
      'auth_welcome_sub': 'Exchange Skills, Improve Competence',
      'auth_nik_label': 'NIK',
      'auth_nik_hint': '16 digit NIK',
      'auth_password_label': 'Password',
      'auth_password_hint': 'Enter password',
      'auth_login_btn': 'Login',
      'auth_no_account': 'Don\'t have an account?',
      'auth_register_link': 'Register Now',
      'auth_personal_data': 'Personal Data',
      'auth_fullname_label': 'Full Name',
      'auth_nickname_label': 'Nickname',
      'auth_gender_label': 'Gender',
      'auth_dob_label': 'Date of Birth',
      'auth_address_title': 'Address',
      'auth_address_label': 'Full Address',
      'auth_city_label': 'City',
      'auth_security_title': 'Security & Bio',
      'auth_confirm_pass_label': 'Confirm Password',
      'auth_bio_label': 'Bio (Optional)',
      'auth_bio_hint': 'Tell us about yourself...',
      'auth_next_btn': 'Next',
      'auth_back_btn': 'Back',
      'auth_register_btn': 'Register',
      'auth_gender_male': 'Male',
      'auth_gender_female': 'Female',
      // Barter
      'trans_title': 'Barter Transactions',
      'tab_sent': 'Sent',
      'tab_received': 'Received',
      'tab_rejected': 'Rejected',
      'tab_history': 'History',
      'filter_all': 'All',
      'filter_waiting': 'Waiting',
      'filter_accepted': 'Accepted',
      'filter_ongoing': 'Ongoing',
      'filter_completed': 'Completed',
      'filter_rejected': 'Rejected',
      'btn_retry': 'Try Again',
      'empty_sent': 'No sent offers yet',
      'empty_received': 'No received offers yet',
      'empty_history': 'No transaction history',
      'empty_rejected': 'No rejected offers',
      'fab_create': 'Create Barter',
      'detail_title': 'Offer Detail',
      'label_code': 'Code',
      'status_waiting_partner': 'Waiting for partner...',
      'label_you_give': 'You Give',
      'label_you_receive': 'You Receive',
      'section_trans_detail': 'Transaction Detail',
      'dialog_upload_title': 'Success!',
      'dialog_upload_success': 'Proof uploaded successfully',
      'dialog_error_title': 'Failed!',
      'dialog_confirm_title': 'Confirm Completion',
      'dialog_confirm_body':
          'Are you sure the barter session is complete? Skillcoins will be transferred after both parties confirm.',
      'btn_cancel': 'Cancel',
      'btn_confirm_yes': 'Yes, Confirm',
      'notif_confirm_success': 'Completion confirmed successfully',
      'create_title_help': 'Request Help',
      'create_title_offer': 'Make Offer',
      'section_session_detail': 'Session Detail',
      'label_duration': 'Duration (hours)',
      'helper_duration': 'How long is the session?',
      'error_required': 'Required',
      'error_min_hour': 'Min. 1 hour',
      'label_date': 'Date',
      'label_time': 'Time',
      'placeholder_date': 'Select Date',
      'placeholder_time': 'Select Time',
      'section_loc_pref': 'Location & Preference',
      'loc_online': 'Online',
      'loc_offline': 'Offline',
      'loc_hybrid': 'Hybrid',
      'hint_link': 'Meeting Link (Zoom/GMeet)',
      'hint_address': 'Full Address',
      'label_notes': 'Notes (Optional)',
      'helper_notes': 'Additional info for partner',
      'btn_send_request': 'Send Request',
      'btn_send_offer': 'Send Offer',
      'msg_success_sent': 'Sent Automatically',
      // Explore
      'explore_title': 'Explore Skills',
      'tab_mastered': 'Mastered',
      'tab_wanted': 'Wanted',
      'search_hint': 'Search skills...',
      'chip_search': 'Search: ',
      'chip_type': 'Type: ',
      'chip_level': 'Level: ',
      'btn_clear_all': 'Clear All',
      'empty_explore_title': 'No skills found',
      'btn_clear_filter': 'Clear Filter',
      // Radar
      'radar_address_fail': 'Failed to load address',
      'radar_address_loading': 'Loading address...',
      'radar_address_unavailable': 'Address unavailable',
      'radar_address_not_found': 'Address not found',
      'radar_user_default': 'SkillBarter User',
      'radar_current_location': 'Current Location',
      'radar_permission_needed': 'Location Permission Required',
      'radar_calibrating': 'Calibrating GPS...',
      'btn_view_profile': 'View Full Profile',
      // Profile
      'user_profile_title': 'User Profile',
      'user_not_found': 'User not found',

      // btn_back reused
      'empty_skills_mastered': 'No skills mastered yet',
      'empty_skills_wanted': 'No skills wanted yet',
      // Add Skill
      'add_skill_title': 'Add New Skill',
      'error_select_category': 'Please select a category first',
      'success_skill_added': '✨ Skill added successfully!',
      'error_add_skill': 'Failed to add skill',
      'section_skill_info': 'Skill Information',
      'label_skill_name': 'Skill Name',
      'label_type': 'Type',
      'label_skill_level': 'Skill Level',
      'label_mastered_expl': 'Mastered (I can teach)',
      'label_wanted_expl': 'Wanted (I want to learn)',
      'level_beginner': 'Beginner',
      'level_intermediate': 'Intermediate',
      'level_advanced': 'Advanced',
      'level_expert': 'Expert',
      'section_additional_details': 'Additional Details',
      'label_price': 'Price per Session (SkillCoin)',
      'label_experience': 'Experience (Years/Projects)',
      'label_description': 'Full Description',
      'label_portfolio': 'Portfolio Link (URL)',
      'btn_save_publish': 'Save & Publish',
      'label_upload_cover': 'Upload Cover Photo',
      'hint_upload_cover': 'Tap to select image',
      'btn_change_photo': 'Change Photo',
      'label_category': 'Skill Category',
      'error_category_required': 'Category is required',
      'label_expiry_date': 'Expiry Date (Optional)',
      // Skill Detail & List
      'skill_detail_title': 'Skill Detail',
      'error_skill_not_found': 'Skill not found',
      'title_my_skills': 'My Skills',
      'btn_add_skill': 'Add Skill',
      'menu_edit': 'Edit',
      'menu_delete': 'Delete',
      'dialog_delete_title': 'Delete Skill',
      'dialog_delete_body':
          'Are you sure you want to delete this skill?\nThis action cannot be undone.',
      // btn_cancel reused
      'btn_delete': 'Delete',
      'label_category_general': 'General',
      'section_detail_info': 'Detail Information',
      'empty_description': 'No description yet',
      'error_open_link': 'Cannot open link',
      'empty_portfolio': 'No portfolio link yet',
      'label_owner': 'Owner',
      'label_unknown': 'Unknown',
      'section_portfolio_gallery': 'Portfolio Gallery',
      'btn_verify_skill': 'Verify Skill',
      'dialog_help_title': 'Confirm Help',
      'label_estimate': 'Estimate',
      'msg_help_info':
          'You will use SkillCoin to request this help without needing to barter your skill.',
      'btn_continue': 'Continue',
      'btn_request_help': 'Request Help',
      'btn_swap_skill': 'Swap Skill',
      'success_skill_deleted': 'Skill deleted successfully',
      'error_delete_skill': 'Failed to delete skill',
      'dialog_verify_title': 'Verify Skill',
      'dialog_verify_body': 'Are you sure you want to verify this skill?',
      'label_verify_cost': 'Verification Cost',
      'btn_verify': 'Verify',
      'success_verify_title': 'Verification Successful!',
      'success_verify_body': 'Skill verified successfully.',
      'msg_coins_used': '10 SkillCoin used',
      'btn_done': 'Done',
      'error_verify_title': 'Verification Failed',
      'btn_close': 'Close',

      // Edit Profile
      'edit_profile_title': 'Edit Profile',
      'edit_profile_subtitle': 'Update your personal information',
      'label_nickname': 'Nickname',
      'label_bio_short': 'Short Bio',
      'hint_bio': 'Tell us a little about yourself...',
      'section_job_edu': 'Job & Education',
      'label_instance': 'Agency / School Name',
      'hint_instance': 'Workplace or school name',
      'label_last_edu': 'Last Education',
      'hint_edu': 'Example: Bachelor of Computer Science',
      'section_pref_other': 'Preferences & Others',
      'label_languages': 'Languages Mastered',
      'hint_languages': 'Example: English, Indonesian',
      'label_pref_loc': 'Location Preference',
      'loc_both': 'Both (Flexible)',
      'loc_meet': 'Offline (Meet in person)',
      'btn_save_changes': 'Save Changes',
      'msg_profile_updated': 'Profile Updated Successfully',

      // Leaderboard
      'leaderboard_title': 'Leaderboard',
      'header_rank': 'Rank',
      'label_your_pos': 'Your Position',
      'empty_leaderboard': 'No leaderboard data',

      // Create Offer
      'section_exchange_skills': 'Skill Exchange',
      'label_you_offer': 'You Offer',
      'label_choose_your_skill': 'Select your skill',
      'label_you_ask': 'You Request',
      'placeholder_select_date': 'Select Date',
      'placeholder_select_time': 'Select Time',
      'create_title_offer': 'Make Offer',
      'create_title_help': 'Request Help',
      'section_session_detail': 'Session Detail',
      'label_duration': 'Duration (hours)',
      'helper_duration': 'e.g. 2',
      'section_loc_pref': 'Location & Preference',
      'loc_online': 'Online',
      'loc_offline': 'Offline',
      'loc_hybrid': 'Hybrid',
      'hint_link': 'Meeting Link',
      'hint_address': 'Address / Location',
      'label_notes': 'Notes / Additional Info',
      'helper_notes': 'Optional',
      'btn_send_offer': 'Send Offer',
      'btn_send_request': 'Send Request',

      // Help Center
      'help_center_title': 'Help Center',
      'tab_faq': 'FAQ',
      'tab_contact_us': 'Contact Us',
      'header_need_help': 'Need Help?',
      'sub_need_help': 'Tell us your problem, our team will help soon.',
      'label_desc_problem': 'Problem Description',
      'hint_desc_problem': 'Explain your issue...',
      'error_desc_required': 'Please explain your issue',
      'label_upload_proof': 'Upload Screenshot (Optional)',
      'faq_q1': 'What is SkillCoin?',
      'faq_a1':
          'SkillCoin is a digital currency within the application used to pay for services or show appreciation to barter partners.',
      'faq_q2': 'How to get SkillCoin?',
      'faq_a2':
          'You can get SkillCoin upon registration (Bonus), or by completing missions and helping others.',
      'faq_q3': 'Can I cancel a transaction?',
      'faq_a3':
          'Yes, as long as the status is "Waiting" or "Ongoing", you can cancel it. However, coins may be refunded or forfeited depending on the conditions.',
      'faq_q4': 'How does the rating system work?',
      'faq_a4':
          'Ratings are given after a transaction is completed. Ratings affect your reputation so that other users can trust you more.',
      'btn_send_report': 'Send Report',
      'msg_sent': 'Sent',
      'error_load_skills': 'Failed to load your skills',
      // Privacy Policy
      'privacy_title_1': '1. Data Collection',
      'privacy_content_1':
          'We collect information you provide directly, such as when you perform identity verification (KYC). This includes Full Name and National ID Number (NIK) as per identity card. We do not collect phone numbers or email addresses for registration.',
      'privacy_title_2': '2. Use of Information',
      'privacy_content_2':
          'We use your NIK solely for identity verification to ensure safety and trust within the barter community. This information is used to prevent fraud and ensure every user is a legitimate individual.',
      'privacy_title_3': '3. Information Sharing',
      'privacy_content_3':
          'We do not share your NIK or personal data with third parties. Your data is stored with high-level encryption and is only accessed for verification purposes by our admin team.',
      'privacy_title_4': '4. Data Security',
      'privacy_content_4':
          'We implement physical, electronic, and procedural security measures to protect your NIK and personal data. Our servers are protected with the latest encryption technology.',

      // Terms & Conditions
      'terms_title_1': '1. Acceptance of Terms',
      'terms_content_1':
          'By accessing and using the SkillBarter application, you agree to be bound by these terms and conditions. If you do not agree with any part of these terms, you may not use our services.',
      'terms_title_2': '2. Identity Verification (NIK)',
      'terms_content_2':
          'Use of certain features requires verification using NIK KTP. You are responsible for providing valid and correct data. Misuse of identity data will be prosecuted according to applicable laws.',
      'terms_title_3': '3. User Conduct',
      'terms_content_3':
          'You agree not to use the service for illegal or unlawful purposes. You must not harass, threaten, or intimidate other users.',
      'terms_title_4': '4. Barter System',
      'terms_content_4':
          'SkillBarter is merely a platform connecting users. Barter agreements are the sole responsibility of the involved parties. We are not responsible for the quality of services bartered.',
      'terms_title_5': '5. Changes to Terms',
      'terms_content_5':
          'We reserve the right to update or change our terms and conditions at any time without prior notice. Your continued use of the service after we post any modifications constitutes your acceptance of those modifications.',
      'legal_last_updated': 'Last updated: February 5, 2026',
      'about_website_title': 'Website',
    },
    'id': {
      'settings_title': 'Pengaturan',
      'common_section': 'Umum',
      'language_tile': 'Bahasa',
      'theme_tile': 'Tema Gelap',
      'theme_subtitle': 'Ganti tampilan ke mode gelap',
      'notifications_section': 'Notifikasi',
      'push_notif': 'Notifikasi Push',
      'push_notif_sub': 'Info barter & chat masuk',
      'email_notif': 'Email Newsletter',
      'email_notif_sub': 'Update fitur & promo menarik',
      'about_section': 'Tentang',
      'app_version': 'Versi Aplikasi',
      'privacy_policy': 'Kebijakan Privasi',
      'terms_conditions': 'Syarat & Ketentuan',
      'account_section': 'Akun',
      'delete_account': 'Hapus Akun',
      'delete_account_sub': 'Tindakan ini tidak dapat dibatalkan',
      'rights_reserved': 'SkillBarter © 2026',
      'select_language': 'Pilih Bahasa',
      // Navigation
      'nav_home': 'Beranda',
      'nav_explore': 'Jelajah',
      'nav_radar': 'Radar',
      'nav_trans': 'Transaksi',
      'nav_profile': 'Profil',
      // Profile
      'info_title': 'Informasi Pribadi',
      'label_nik': 'NIK',
      'label_gender': 'Jenis Kelamin',
      'gender_male': 'Laki-laki',
      'gender_female': 'Perempuan',
      'label_dob': 'Tanggal Lahir',
      'label_city': 'Kota',
      'label_job': 'Pekerjaan',
      'label_edu': 'Pendidikan',
      'menu_password': 'Ubah Password',
      'menu_help': 'Pusat Bantuan',
      'stat_trans': 'Transaksi',
      'stat_hours': 'Jam',
      // Home
      'welcome_sub': 'Mau tukar skill apa hari ini?',
      'stat_rating': 'Rating',
      'stat_coins': 'SkillCoin',
      'stat_hours_contrib': 'Jam Kontribusi',
      'quick_actions': 'Aksi Cepat',
      'action_add_skill': 'Tambah Skill',
      'action_add_skill_sub': 'Mulai berbagi',
      'action_search': 'Cari Skill',
      'action_search_sub': 'Temukan mentor',
      'action_leaderboard': 'Leaderboard',
      'action_leaderboard_sub': 'Top pengguna',
      'action_history': 'Riwayat',
      'action_history_sub': 'Log aktivitas',
      // Auth
      'auth_login_title': 'Masuk',
      'auth_register_title': 'Daftar Akun',
      'auth_welcome_title': 'SkillBarter',
      'auth_welcome_sub': 'Tukar Keahlian, Tingkatkan Skill',
      'auth_nik_label': 'NIK',
      'auth_nik_hint': '16 digit NIK',
      'auth_password_label': 'Password',
      'auth_password_hint': 'Masukkan password',
      'auth_login_btn': 'Login',
      'auth_no_account': 'Belum punya akun? ',
      'auth_register_link': 'Daftar Sekarang',
      'auth_personal_data': 'Data Pribadi',
      'auth_fullname_label': 'Nama Lengkap',
      'auth_nickname_label': 'Nama Panggilan',
      'auth_gender_label': 'Jenis Kelamin',
      'auth_dob_label': 'Tanggal Lahir',
      'auth_address_title': 'Alamat',
      'auth_address_label': 'Alamat Lengkap',
      'auth_city_label': 'Kota',
      'auth_security_title': 'Keamanan & Bio',
      'auth_confirm_pass_label': 'Konfirmasi Password',
      'auth_bio_label': 'Bio (Opsional)',
      'auth_bio_hint': 'Ceritakan tentang diri Anda...',
      'auth_next_btn': 'Lanjut',
      'auth_back_btn': 'Kembali',
      'auth_register_btn': 'Daftar',
      'auth_gender_male': 'Laki-laki',
      'auth_gender_female': 'Perempuan',
      // Barter
      'trans_title': 'Transaksi Barter',
      'tab_sent': 'Terkirim',
      'tab_received': 'Diterima',
      'tab_rejected': 'Ditolak',
      'tab_history': 'Riwayat',
      'filter_all': 'Semua',
      'filter_waiting': 'Menunggu',
      'filter_accepted': 'Diterima',
      'filter_ongoing': 'Berlangsung',
      'filter_completed': 'Selesai',
      'filter_rejected': 'Ditolak',
      'btn_retry': 'Coba Lagi',
      'empty_sent': 'Belum ada penawaran terkirim',
      'empty_received': 'Belum ada penawaran diterima',
      'empty_history': 'Belum ada riwayat transaksi',
      'empty_rejected': 'Tidak ada penawaran yang ditolak',
      'fab_create': 'Buat Barter',
      'detail_title': 'Detail Penawaran',
      'label_code': 'Kode',
      'status_waiting_partner': 'Menunggu partner...',
      'label_you_give': 'Anda Beri',
      'label_you_receive': 'Anda Terima',
      'section_trans_detail': 'Detail Transaksi',
      'dialog_upload_title': 'Berhasil!',
      'dialog_upload_success': 'Bukti pelaksanaan berhasil diupload',
      'dialog_error_title': 'Gagal!',
      'dialog_confirm_title': 'Konfirmasi Penyelesaian',
      'dialog_confirm_body':
          'Apakah Anda yakin sesi barter sudah selesai dilaksanakan? Setelah kedua pihak konfirmasi, skillcoin akan ditransfer.',
      'btn_cancel': 'Batal',
      'btn_confirm_yes': 'Ya, Konfirmasi',
      'notif_confirm_success': 'Penyelesaian berhasil dikonfirmasi',
      'create_title_help': 'Minta Bantuan',
      'create_title_offer': 'Buat Penawaran',
      'section_session_detail': 'Detail Sesi',
      'label_duration': 'Durasi (jam)',
      'helper_duration': 'Berapa lama sesi barter?',
      'error_required': 'Wajib diisi',
      'error_min_hour': 'Min. 1 jam',
      'label_date': 'Tanggal',
      'label_time': 'Waktu',
      'placeholder_date': 'Pilih Tgl',
      'placeholder_time': 'Pilih Jam',
      'section_loc_pref': 'Lokasi & Preferensi',
      'loc_online': 'Online',
      'loc_offline': 'Offline',
      'loc_hybrid': 'Hybrid',
      'hint_link': 'Link Meeting (Zoom/GMeet)',
      'hint_address': 'Alamat Lengkap',
      'label_notes': 'Catatan (Opsional)',
      'helper_notes': 'Info tambahan untuk partner',
      'btn_send_request': 'Kirim Permintaan',
      'btn_send_offer': 'Kirim Penawaran',
      'msg_success_sent': 'Berhasil Dikirim',
      // Explore
      'explore_title': 'Jelajah Skill',
      'tab_mastered': 'Dikuasai',
      'tab_wanted': 'Dicari',
      'search_hint': 'Cari skill...',
      'chip_search': 'Pencarian: ',
      'chip_type': 'Tipe: ',
      'chip_level': 'Tingkat: ',
      'btn_clear_all': 'Hapus Semua',
      'empty_explore_title': 'Tidak ada skill ditemukan',
      'btn_clear_filter': 'Hapus Filter',
      // Radar
      'radar_address_fail': 'Gagal memuat alamat',
      'radar_address_loading': 'Memuat alamat...',
      'radar_address_unavailable': 'Alamat tidak tersedia',
      'radar_address_not_found': 'Alamat tidak ditemukan',
      'radar_user_default': 'User SkillBarter',
      'radar_current_location': 'Lokasi Terkini',
      'radar_permission_needed': 'Izin Lokasi diperlukan',
      'radar_calibrating': 'Mengkalibrasi GPS...',
      'btn_view_profile': 'Lihat Profil Lengkap',
      'user_profile_title': 'Profil User',
      'user_not_found': 'User tidak ditemukan',
      // btn_back reused
      'empty_skills_mastered': 'Belum ada skill dikuasai',
      'empty_skills_wanted': 'Belum ada skill dicari',
      // Add Skill
      'add_skill_title': 'Tambah Skill Baru',
      'error_select_category': 'Silakan pilih kategori terlebih dahulu',
      'success_skill_added': '✨ Skill berhasil ditambahkan!',
      'error_add_skill': 'Gagal menambahkan skill',
      'section_skill_info': 'Informasi Skill',
      'label_skill_name': 'Nama Keahlian',
      'label_type': 'Tipe',
      'label_skill_level': 'Tingkat Keahlian',
      'label_mastered_expl': 'Dikuasai (Saya bisa)',
      'label_wanted_expl': 'Dicari (Saya butuh)',
      'level_beginner': 'Pemula',
      'level_intermediate': 'Menengah',
      'level_advanced': 'Mahir',
      'level_expert': 'Ahli',
      'section_additional_details': 'Detail Tambahan',
      'label_price': 'Harga per Sesi (SkillCoin)',
      'label_experience': 'Pengalaman (Tahun/Proyek)',
      'label_description': 'Deskripsi Lengkap',
      'label_portfolio': 'Link Portofolio (URL)',
      'btn_save_publish': 'Simpan & Publikasikan',
      'label_upload_cover': 'Upload Foto Sampul',
      'hint_upload_cover': 'Tap untuk memilih gambar',
      'btn_change_photo': 'Ganti Foto',
      'label_category': 'Kategori Keahlian',
      'error_category_required': 'Kategori wajib dipilih',
      'label_expiry_date': 'Tanggal Berakhir (Opsional)',
      // Skill Detail & List
      'skill_detail_title': 'Detail Skill',
      'error_skill_not_found': 'Skill tidak ditemukan',
      'title_my_skills': 'Keahlian Saya',
      'btn_add_skill': 'Tambah Skill',
      'menu_edit': 'Edit',
      'menu_delete': 'Hapus',
      'dialog_delete_title': 'Hapus Skill',
      'dialog_delete_body':
          'Apakah Anda yakin ingin menghapus skill ini?\nTindakan ini tidak dapat dibatalkan.',
      // btn_cancel reused
      'btn_delete': 'Hapus',

      // Edit Profile
      'edit_profile_title': 'Edit Profil',
      'edit_profile_subtitle': 'Perbarui informasi data diri Anda',
      'label_nickname': 'Nama Panggilan',
      'label_bio_short': 'Bio Singkat',
      'hint_bio': 'Ceritakan sedikit tentang dirimu...',
      'section_job_edu': 'Pekerjaan & Pendidikan',
      'label_instance': 'Nama Instansi / Sekolah',
      'hint_instance': 'Nama tempat kerja atau sekolah',
      'label_last_edu': 'Pendidikan Terakhir',
      'hint_edu': 'Contoh: S1 Teknik Informatika',
      'section_pref_other': 'Preferensi & Lainnya',
      'label_languages': 'Bahasa yang Dikuasai',
      'hint_languages': 'Contoh: Indonesia, Inggris',
      'label_pref_loc': 'Preferensi Lokasi',
      'loc_both': 'Keduanya (Fleksibel)',
      'loc_meet': 'Offline (Bertemu Langsung)',
      'btn_save_changes': 'Simpan Perubahan',
      'msg_profile_updated': 'Profil Berhasil Diperbarui',

      // Leaderboard
      'leaderboard_title': 'Leaderboard',
      'header_rank': 'Peringkat',
      'label_your_pos': 'Posisi Anda',
      'empty_leaderboard': 'Tidak ada data leaderboard',

      // Create Offer
      'section_exchange_skills': 'Pertukaran Skill',
      'label_you_offer': 'Anda Tawarkan',
      'label_choose_your_skill': 'Pilih skill Anda',
      'label_you_ask': 'Anda Minta',
      'placeholder_select_date': 'Pilih Tgl',
      'placeholder_select_time': 'Pilih Jam',
      'create_title_offer': 'Buat Penawaran',
      'create_title_help': 'Minta Bantuan',
      'section_session_detail': 'Detail Sesi',
      'label_duration': 'Durasi (jam)',
      'helper_duration': 'cth. 2',
      'section_loc_pref': 'Lokasi & Preferensi',
      'loc_online': 'Online',
      'loc_offline': 'Offline',
      'loc_hybrid': 'Hybrid',
      'hint_link': 'Link Pertemuan',
      'hint_address': 'Alamat / Lokasi',
      'label_notes': 'Catatan / Info Tambahan',
      'helper_notes': 'Opsional',
      'btn_send_offer': 'Kirim Penawaran',
      'btn_send_request': 'Kirim Permintaan',

      // Help Center
      'help_center_title': 'Pusat Bantuan',
      'tab_faq': 'FAQ',
      'tab_contact_us': 'Hubungi Kami',
      'header_need_help': 'Butuh Bantuan?',
      'sub_need_help': 'Ceritakan masalah Anda, tim kami akan segera membantu.',
      'label_desc_problem': 'Deskripsi Masalah',
      'hint_desc_problem': 'Jelaskan kendala Anda...',
      'error_desc_required': 'Mohon jelaskan kendala Anda',
      'label_upload_proof': 'Upload Screenshot (Opsional)',
      'faq_q1': 'Apa itu SkillCoin?',
      'faq_a1':
          'SkillCoin adalah mata uang digital dalam aplikasi yang digunakan untuk membayar jasa atau memberikan apresiasi kepada partner barter.',
      'faq_q2': 'Bagaimana cara mendapatkan SkillCoin?',
      'faq_a2':
          'Anda akan mendapatkan SkillCoin saat pertama kali mendaftar (Bonus), atau dengan menyelesaikan misi dan membantu orang lain.',
      'faq_q3': 'Apakah saya bisa membatalkan transaksi?',
      'faq_a3':
          'Ya, selama status transaksi masih "Menunggu" atau "Berlangsung", Anda bisa membatalkannya. Namun koin mungkin akan dikembalikan atau hangus tergantung kondisi.',
      'faq_q4': 'Bagaimana sistem rating bekerja?',
      'faq_a4':
          'Rating diberikan setelah transaksi selesai. Rating mempengaruhi reputasi Anda agar lebih dipercaya oleh pengguna lain.',
      'btn_send_report': 'Kirim Laporan',
      'msg_sent': 'Terkirim',
      'error_load_skills': 'Gagal memuat skill Anda',
      'label_category_general': 'Umum',
      'section_detail_info': 'Informasi Detail',
      'empty_description': 'Belum ada deskripsi',
      'error_open_link': 'Tidak dapat membuka link',
      'empty_portfolio': 'Belum ada link portfolio',
      'label_owner': 'Pemilik',
      'label_unknown': 'Unknown',
      'section_portfolio_gallery': 'Galeri Portfolio',
      'btn_verify_skill': 'Verifikasi Skill',
      'dialog_help_title': 'Konfirmasi Bantuan',
      'label_estimate': 'Estimasi',
      'msg_help_info':
          'Anda akan menggunakan SkillCoin untuk meminta bantuan ini tanpa perlu menawarkan skill Anda.',
      'btn_continue': 'Lanjutkan',
      'btn_request_help': 'Minta Bantuan',
      'btn_swap_skill': 'Tukar Skill',
      'success_skill_deleted': 'Skill berhasil dihapus',
      'error_delete_skill': 'Gagal menghapus skill',
      'dialog_verify_title': 'Verifikasi Skill',
      'dialog_verify_body': 'Apakah Anda yakin ingin memverifikasi skill ini?',
      'label_verify_cost': 'Biaya Verifikasi',
      'btn_verify': 'Verifikasi',
      'success_verify_title': 'Verifikasi Berhasil!',
      'success_verify_body': 'Skill kini memiliki lencana terverifikasi.',
      'msg_coins_used': '10 SkillCoin digunakan',
      'btn_done': 'Selesai',
      'error_verify_title': 'Verifikasi Gagal',
      'btn_close': 'Tutup',
      'btn_close': 'Tutup',
      // Privacy Policy
      'privacy_title_1': '1. Pengumpulan Data',
      'privacy_content_1':
          'Kami mengumpulkan informasi yang Anda berikan secara langsung, seperti saat Anda melakukan verifikasi identitas (KYC). Informasi ini meliputi Nama Lengkap dan Nomor Induk Kependudukan (NIK) sesuai KTP. Kami tidak mengumpulkan nomor telepon atau alamat email untuk pendaftaran.',
      'privacy_title_2': '2. Penggunaan Informasi',
      'privacy_content_2':
          'Kami menggunakan NIK KTP semata-mata untuk verifikasi identitas guna menjamin keamanan dan kepercayaan dalam komunitas barter. Informasi ini digunakan untuk mencegah penipuan dan memastikan setiap pengguna adalah individu yang sah.',
      'privacy_title_3': '3. Berbagi Informasi',
      'privacy_content_3':
          'Kami tidak membagikan NIK atau data pribadi Anda kepada pihak ketiga. Data Anda disimpan dengan enkripsi tingkat tinggi dan hanya diakses untuk keperluan verifikasi oleh tim admin kami.',
      'privacy_title_4': '4. Keamanan Data',
      'privacy_content_4':
          'Kami menerapkan langkah-langkah keamanan fisik, elektronik, dan prosedural untuk melindungi NIK dan data pribadi Anda. Server kami dilindungi dengan teknologi enkripsi terkini.',

      // Terms & Conditions
      'terms_title_1': '1. Penerimaan Syarat',
      'terms_content_1':
          'Dengan mengakses dan menggunakan aplikasi SkillBarter, Anda setuju untuk terikat oleh syarat dan ketentuan ini. Jika Anda tidak setuju dengan bagian mana pun dari syarat ini, Anda tidak boleh menggunakan layanan kami.',
      'terms_title_2': '2. Verifikasi Identitas (NIK)',
      'terms_content_2':
          'Penggunaan fitur tertentu memerlukan verifikasi menggunakan NIK KTP. Anda bertanggung jawab untuk memberikan data yang valid dan benar. Penyalahgunaan data identitas akan ditindak sesuai hukum yang berlaku.',
      'terms_title_3': '3. Perilaku Pengguna',
      'terms_content_3':
          'Anda setuju untuk tidak menggunakan layanan untuk tujuan ilegal atau melanggar hukum. Anda tidak boleh melecehkan, mengancam, atau mengintimidasi pengguna lain.',
      'terms_title_4': '4. Sistem Barter',
      'terms_content_4':
          'SkillBarter hanyalah platform yang menghubungkan pengguna. Kesepakatan barter adalah tanggung jawab penuh antara pihak-pihak yang terlibat. Kami tidak bertanggung jawab atas kualitas layanan yang dibarterkan.',
      'terms_title_5': '5. Perubahan Syarat',
      'terms_content_5':
          'Kami berhak untuk memperbarui atau mengubah syarat dan ketentuan kami kapan saja tanpa pemberitahuan sebelumnya. Penggunaan berkelanjutan Anda atas layanan setelah kami memposting modifikasi apa pun pada syarat dan ketentuan merupakan penerimaan Anda terhadap modifikasi tersebut.',
      'legal_last_updated': 'Terakhir diperbarui: 5 Februari 2026',
      'about_website_title': 'Situs Web',
    },
  };

  Future<bool> load() async {
    // For now we use static maps, so just return true
    _localizedStrings =
        _localizedValues[locale.languageCode] ?? _localizedValues['id']!;
    return true;
  }

  String translate(String key) {
    return _localizedStrings[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'id'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    AppLocalizations localizations = AppLocalizations(locale);
    await localizations.load();
    return localizations;
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
